version: '3.1'

services:
  db:
    image: mariadb:10.7
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"   # Mappage explicite du port 3307 de l'hôte au port 3306 du conteneur
  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
